package DataSource;
// Generated Apr 7, 2015 11:04:57 PM by Hibernate Tools 3.6.0

import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;




/**
 * UserGateway generated by hbm2java
 */
public class UserGateway  implements java.io.Serializable {


     private int uid;
     private String uuser;
     private String upassword;
     private String uname;
     private String uaddres;
     private int ucnp;
   //  private Session s = NewHibernateUtil.getSessionFactory().openSession();

    public UserGateway() {
       super();
       this.uid = 0;
       this.uuser = "";
       this.upassword = "";
       this.uname = "";
       this.uaddres = "";
       this.ucnp = 0;
    }

    public UserGateway(int uid, String uuser, String upassword, String uname, String uaddres, int ucnp) {
       this.uid = uid;
       this.uuser = uuser;
       this.upassword = upassword;
       this.uname = uname;
       this.uaddres = uaddres;
       this.ucnp = ucnp;
    }
   
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public String getUuser() {
        return this.uuser;
    }
    
    public void setUuser(String uuser) {
        this.uuser = uuser;
    }
    public String getUpassword() {
        return this.upassword;
    }
    
    public void setUpassword(String upassword) {
        this.upassword = upassword;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getUaddres() {
        return this.uaddres;
    }
    
    public void setUaddres(String uaddres) {
        this.uaddres = uaddres;
    }
    public int getUcnp() {
        return this.ucnp;
    }
    
    public void setUcnp(int ucnp) {
        this.ucnp = ucnp;
    }
     @Override
    public String toString()
    {
        return  (uid + " | " + uuser + " | " + upassword + " | " + uname + " | " + uaddres + " | " + ucnp);
    }
    
     public boolean insert(int uid, String uuser, String upassword, String uname, String uaddres, int ucnp){
     
      Session s = NewHibernateUtil.getSessionFactory().openSession();
      boolean done = false;    
      Transaction tx = null;
      try{
         tx = s.beginTransaction();
         s.save(new UserGateway(uid,uuser,upassword,uname,uaddres,ucnp));
         done = true;
         tx.commit();
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
      }finally {
         s.close(); 
      }
        return true;
    }
    public boolean update(int uid, String uuser, String upassword, String uname, String uaddres, int ucnp){
    
     boolean done = false;
     Transaction tx = null;
     Session s = NewHibernateUtil.getSessionFactory().openSession();
      try{
         tx = s.beginTransaction();
         s.update(new UserGateway(uid,uuser,upassword,uname,uaddres,ucnp));
         done = true;
         tx.commit();
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
      }finally {
         s.close(); 
      }
        return done;
    }
    
     public boolean delete(int uid, String uuser, String upassword, String uname, String uaddres, int ucnp){
    
     boolean done = false;
     Session s = NewHibernateUtil.getSessionFactory().openSession();
     Transaction tx = null;
      try{
         tx = s.beginTransaction();
         s.delete(new UserGateway(uid,uuser,upassword,uname,uaddres,ucnp));
         done = true;
         tx.commit();
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
      }finally {
         s.close(); 
      }
        return done;
    }

}


